name: core-api ci

on:
  push:
    branches: [ master, pre_*, ft_*, release/* ]
    paths: ['src/core-api/**']
  pull_request:
    branches: [ master, pre_*, ft_*, release/* ]
    paths: ['src/core-api/**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache-dependency-path: src/core-api/go.sum

    - name: Build
      run: make build
      working-directory: src/core-api

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2
        working-directory: src/core-api
    
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.19.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: 'src/core-api'

    - name: Test
      run: make dep && make test
      working-directory: src/core-api